# Generated by Django 4.0.4 on 2023-05-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forclosure',
            name='attachment',
        ),
    ]
