# Generated by Django 4.0.4 on 2023-05-29 20:14

from django.db import migrations, models
import workflowapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0004_alter_forclosure_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='attachment',
            field=models.FileField(default=workflowapp.models.get_default_attachment, upload_to='attachments/'),
        ),
    ]
