# Generated by Django 4.0.4 on 2023-05-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0005_alter_forclosure_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
