# Generated by Django 4.0.4 on 2023-06-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0009_alter_forclosure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosurelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forclosure_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
