# Generated by Django 4.0.4 on 2023-06-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0011_alter_forclosure_user_alter_forclosurelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forclosure',
            name='reviewer',
            field=models.ForeignKey(default=3, limit_choices_to={'groups__name': 'Supervisors'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_forclosures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
