# Generated by Django 4.0.4 on 2023-06-03 15:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0012_forclosure_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('cancelled', 'Cancelled'), ('first_reviewed', 'First_reviewed'), ('second_reviewed', 'Second_reviewed'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('approved', 'Approved')], default='initiated', max_length=50),
        ),
    ]
