# Generated by Django 4.0.4 on 2023-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0016_alter_forclosure_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.RemoveField(
            model_name='forclosure',
            name='attachment',
        ),
        migrations.AddField(
            model_name='forclosure',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='workflowapp.attachment'),
        ),
    ]
