# Generated by Django 4.0.4 on 2023-06-05 15:01

from django.db import migrations, models
import workflowapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0017_attachment_remove_forclosure_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forclosure',
            name='attachments',
        ),
        migrations.AddField(
            model_name='forclosure',
            name='attachment',
            field=models.FileField(default=workflowapp.models.get_default_attachment, upload_to='attachments/'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
