# Generated by Django 4.0.4 on 2023-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0019_remove_forclosure_attachment_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_role_id', models.IntegerField()),
                ('nssf_no', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('registry_dt', models.DateField()),
                ('party_role_type_descr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
    ]
