# Generated by Django 4.0.4 on 2023-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0020_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='registry_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
