# Generated by Django 4.0.4 on 2023-06-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0022_alter_forclosure_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='forclosure',
            name='next_action_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Assessors'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_action_forclosures', to=settings.AUTH_USER_MODEL),
        ),
    ]
