# Generated by Django 4.0.4 on 2023-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0023_forclosure_next_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='reason',
            field=models.CharField(choices=[('nira', 'Employer closed in NIRA'), ('others', 'Others')], max_length=30),
        ),
    ]
