# Generated by Django 4.0.4 on 2023-08-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0024_alter_forclosure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('recorded', 'Recorded'), ('forwarded', 'forwarded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recorded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer_name', models.CharField(max_length=130)),
                ('nssf_no', models.CharField(max_length=130)),
                ('activity_done', multiselectfield.db.fields.MultiSelectField(choices=[('member_reg', 'Member registration'), ('assessment', 'Assessment'), ('fl', 'Financial Literacy'), ('roadshow', 'Roadshow'), ('audit', 'Compliance Audit'), ('inspection', 'Inspection'), ('senstisation', 'Senstisation'), ('support', 'Support'), ('recovery', 'Collections recovery'), ('emp_reg', 'Employer registration'), ('mapping', 'Mapping'), ('suspe', 'Suspence clearence'), ('closure', 'Employer closure')], max_length=110)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_engagements', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Generalcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('recorded', 'Recorded'), ('forwarded', 'forwarded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='recorded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.CharField(max_length=130)),
                ('action_date', models.DateTimeField()),
                ('any_other_info', models.CharField(max_length=130)),
                ('remark', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_generalcases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalcases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forclosure',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='forclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.forclosure'),
        ),
        migrations.AlterField(
            model_name='forclosure',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneralcaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflowapp.generalcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalcase_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflowapp.engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.engagement'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='generalcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflowapp.generalcase'),
        ),
    ]
