# Generated by Django 4.0.4 on 2023-08-08 08:43

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0025_engagement_generalcase_forclosure_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclosure',
            name='state',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('cancelled', 'Cancelled'), ('first_reviewed', 'First_reviewed'), ('resubmited', 'Resubmited'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('approved', 'Approved'), ('authorise', 'Authorised')], default='initiated', max_length=50),
        ),
    ]
