# Generated by Django 4.0.4 on 2023-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0026_alter_forclosure_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='monthly_contributions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
