# Generated by Django 4.0.4 on 2023-08-09 07:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0027_engagement_members_engagement_monthly_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='activity_done',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('member_reg', 'Member registration'), ('assessment', 'Assessment'), ('fl', 'Financial Literacy'), ('roadshow', 'Roadshow'), ('audit', 'Compliance Audit'), ('inspection', 'Inspection'), ('senstisation', 'Senstisation'), ('support', 'Support'), ('recovery', 'Collections recovery'), ('emp_reg', 'Employer registration'), ('mapping', 'Mapping'), ('suspe', 'Suspence clearence'), ('closure', 'Employer closure'), ('records', 'Update records')], max_length=118),
        ),
        migrations.AlterField(
            model_name='forclosure',
            name='reason',
            field=models.CharField(choices=[('nira', 'Employer closed in URSB'), ('others', 'Others')], max_length=30),
        ),
    ]
