# Generated by Django 4.0.4 on 2023-08-22 10:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0028_alter_engagement_activity_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='activity_done',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('member_reg', 'Member registration'), ('assessment', 'Assessment'), ('fl', 'Financial Literacy'), ('roadshow', 'Roadshow'), ('audit', 'Compliance Audit'), ('inspection', 'Inspection'), ('senstisation', 'Senstisation'), ('support', 'Support'), ('recovery', 'Collections recovery'), ('emp_reg', 'Employer registration'), ('mapping', 'Mapping'), ('suspe', 'Suspence clearence'), ('closure', 'Employer closure'), ('records', 'Update records'), ('visit', 'Physical visit'), ('benefits', 'Benefits Verification')], max_length=133),
        ),
    ]
