# Generated by Django 4.0.4 on 2023-09-12 08:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0030_alter_engagement_activity_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='activity_done',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('member_reg', 'Member registration'), ('assessment', 'Assessment'), ('fl', 'Financial Literacy'), ('roadshow', 'Roadshow'), ('audit', 'Compliance Audit'), ('inspection', 'Inspection'), ('support', 'Support'), ('recovery', 'Collections recovery'), ('emp_reg', 'Employer registration'), ('suspe', 'Suspence clearence'), ('records', 'Update records'), ('paye_nssf', 'PAYE vs NSSF Reconciliation'), ('benefits', 'Benefits Verification'), ('zero_audit', 'Zero value audit'), ('legal', 'Sent to legal'), ('legacy', 'Legacy audit file closure'), ('no_deed', 'Full no deed recovery')], max_length=140),
        ),
    ]
