# Generated by Django 4.0.4 on 2024-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0033_engagement_reason_for_non_compliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='reason_for_non_compliance',
            field=models.CharField(blank=True, choices=[('inconsistent_funding', 'Inconsistent funding from government/donors'), ('covid19_effects', 'Covid-19 effects'), ('economic_strain', 'Economic strain and cash flow challenges'), ('employer_not_started', 'Employer was registered but hasn’t started operating'), ('unable_to_locate_employer', 'Inability to locate employer/briefcase company'), ('hard_to_reach_employer', 'Hard to reach employer (very far)'), ('high_employer_to_rm_ratio', 'High employer to RM ratio'), ('ignorance_of_nssf_law', 'Ignorance of the NSSF law'), ('informal_employer_closure', 'Informal employer closure'), ('informal_employments', 'Informal employments (casual laborers)'), ('lack_of_trust_in_nssf', 'Lack of trust in the NSSF brand'), ('non_payment_during_school_holidays', 'Non-payment during school holidays'), ('system_breakdown', 'Painful system experiences and breakdown/internet connectivity issues'), ('political_instability', 'Political instability'), ('political_interference', 'Political interference and restricted access to employer premises'), ('stubborn_employer', 'Stubborn and adamant employer'), ('unfavorable_registration_requirements', 'Unfavorable registration requirements for new members and employers'), ('occasional_delays', 'Occasional delays in remitting NSSF contributions')], max_length=50, null=True),
        ),
    ]
