# Generated by Django 4.0.4 on 2024-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0034_alter_engagement_reason_for_non_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='engaged_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='engaged_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
