# Generated by Django 4.0.4 on 2024-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0035_engagement_engaged_email_engagement_engaged_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='engaged_person',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
